# Generated by Django 3.2.25 on 2025-11-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0002_departmentregister_details_designationregister_details_employeeregister_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_email_primary', models.EmailField(blank=True, default='client@gmail.com', max_length=254, null=True)),
                ('client_email_alter', models.EmailField(blank=True, default='client@gmail2.com', max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_phone_alter', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_place', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_profile', models.ImageField(default='', upload_to='client/profile')),
                ('client_bussiness_name', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_bussiness_email_primary', models.EmailField(blank=True, default='client@gmail.com', max_length=254, null=True)),
                ('client_bussiness_email_alter', models.EmailField(blank=True, default='client@gmail2.com', max_length=254, null=True)),
                ('client_bussiness_phone', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_bussiness_phone_alter', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_bussiness_website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_place', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_files', models.ImageField(default='', upload_to='client/files')),
                ('bussiness_logo', models.ImageField(default='', upload_to='client/logo')),
                ('more_description', models.TextField(blank=True, default='', null=True)),
                ('client_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('client_status', models.IntegerField(default=0)),
                ('work_reg_status', models.IntegerField(default=0)),
                ('client_reg_date', models.DateField(auto_now=True, null=True)),
                ('compId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(blank=True, default='', null=True)),
                ('work_create_time', models.TimeField(auto_now_add=True, null=True)),
                ('work_file', models.FileField(default='', upload_to='work/files')),
                ('work_progress', models.IntegerField(default=0)),
                ('work_allocate_status', models.IntegerField(default=0)),
                ('work_status', models.IntegerField(default=0)),
                ('work_create_date', models.DateField(null=True)),
                ('work_end_date', models.DateField(null=True)),
                ('allocated_emp', models.ManyToManyField(related_name='works_allocated', to='DMCoreapp.EmployeeRegister_Details')),
                ('clientId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clientregister')),
                ('wcompId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('task_description', models.TextField(blank=True, default='', null=True)),
                ('task_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('task_status', models.IntegerField(default=0)),
                ('task_add_date', models.DateField(auto_now=True, null=True)),
                ('comp_taskid', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTask_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('task_description', models.TextField(blank=True, default='', null=True)),
                ('task_file', models.FileField(default='', upload_to='work/task/files')),
                ('task_allocate_status', models.IntegerField(default=0)),
                ('task_total_progress', models.IntegerField(default=0)),
                ('task_status', models.IntegerField(default=0)),
                ('task_create_date', models.DateField(null=True)),
                ('cTcompId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.businessregister_details')),
                ('client_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clientregister')),
                ('work_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.workregister')),
            ],
        ),
    ]
