# Generated by Django 3.2.25 on 2025-12-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0003_clientregister_clienttask_register_work_task_workregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_status', models.IntegerField(default=0)),
                ('allocation_date', models.DateField(null=True)),
                ('allocatEmp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
                ('allocat_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeRegister', to='DMCoreapp.employeeregister_details')),
            ],
        ),
    ]
