# Generated by Django 3.2.25 on 2025-12-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0004_allocation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, default='', null=True)),
                ('end_time', models.TimeField(blank=True, default='', null=True)),
                ('schedule_head', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('todo_content', models.TextField(blank=True, default='', null=True)),
                ('log_time', models.TimeField(auto_now_add=True, null=True)),
                ('schedule_status', models.IntegerField(default=0)),
                ('schedule_date', models.DateField(null=True)),
                ('emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('end_date', models.DateField(blank=True, default='', null=True)),
                ('leave_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('leave_reason', models.TextField(blank=True, default='', null=True)),
                ('no_of_days', models.IntegerField(default=0)),
                ('leave_status', models.IntegerField(default=0)),
                ('leave_apply_date', models.DateField(null=True)),
                ('leave_statuChange_date', models.DateField(null=True)),
                ('leave_request_file', models.FileField(default='', upload_to='leave\\files')),
                ('emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
    ]
