# Generated by Django 3.2.25 on 2025-12-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0005_employeeleave_employeeschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(default=0)),
                ('from_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('feedback_content', models.TextField(blank=True, default='', null=True)),
                ('feedback_date', models.DateField(null=True)),
                ('feedback_emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_from_id', models.IntegerField(default=0)),
                ('act_from_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('act_reason', models.TextField(blank=True, default='', null=True)),
                ('act_head', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('act_content', models.TextField(blank=True, default='', null=True)),
                ('action_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('act_emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
    ]
