# Generated by Django 3.2.25 on 2026-03-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0006_actiontaken_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaint_head', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('compaint_content', models.TextField(blank=True, default='', null=True)),
                ('complaint_date', models.DateField(auto_now=True, null=True)),
                ('action', models.TextField(blank=True, default='', null=True)),
                ('action_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('complaint_emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
    ]
