# Generated by Django 3.2.25 on 2026-03-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0007_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_head', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_description', models.TextField(blank=True, null=True)),
                ('target', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_collection/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.workregister')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.IntegerField(default=0)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('work_type', models.CharField(default='single', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_allocation/')),
                ('lead_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMCoreapp.leadcollection')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clienttask_register')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.workregister')),
            ],
        ),
    ]
