# Generated by Django 3.2.25 on 2026-03-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0008_leadallocation_leadcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='text', max_length=50)),
                ('field_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='DMCoreapp.leadcollection')),
            ],
        ),
        migrations.CreateModel(
            name='LeadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Incomplete', 'Incomplete'), ('Waste', 'Waste')], default='Unverified', max_length=15)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMCoreapp.employeeregister_details')),
                ('lead_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='DMCoreapp.leadcollection')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_leads', to='DMCoreapp.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='LeadRowValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.leadfield')),
                ('lead_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='DMCoreapp.leadrow')),
            ],
        ),
    ]
