# Generated by Django 3.2.25 on 2026-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0009_leadfield_leadrow_leadrowvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamleadallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_allocation/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='DMCoreapp.employeeregister_details')),
                ('lead_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMCoreapp.leadcollection')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clienttask_register')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.workregister')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target', models.IntegerField(default=0)),
                ('work_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='daily_work/')),
                ('verified_target', models.IntegerField(default=0)),
                ('verification', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.teamleadallocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clienttask_register')),
            ],
        ),
    ]
