# Generated by Django 3.2.25 on 2026-04-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0010_dailywork_teamleadallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadallocation',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadallocation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='progressreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('progress', models.IntegerField()),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='weekly_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.teamleadallocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWork2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target', models.IntegerField(default=0)),
                ('work_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='daily_work/')),
                ('verified_target', models.IntegerField(default=0)),
                ('verification', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.employeeregister_details')),
                ('singleallocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.leadallocation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.clienttask_register')),
            ],
        ),
    ]
