# Generated by Django 3.2.25 on 2026-04-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0012_followupstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrow',
            name='is_recall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadrow',
            name='is_waste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadrow',
            name='waste_marked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadrow',
            name='waste_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadrow',
            name='waste_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='followUpUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_update_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('call_record', models.FileField(blank=True, null=True, upload_to='followup_calls/')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_close', models.BooleanField(default=False)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMCoreapp.leadrow')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMCoreapp.followupstatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMCoreapp.employeeregister_details')),
            ],
        ),
    ]
