# Generated by Django 4.2 on 2026-05-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMCoreapp', '0014_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrow',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
