from django.urls import path,re_path
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
   path("",views.index,name="index"),
   path('login/', views.login_view, name='login'),
   path('business-register/', views.business_register, name='business_register'),
   path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
   path('check-company-id/', views.check_company_id, name='check_company_id'),
   path('check-email/', views.check_email, name='check_email'),
   path('head-dashboard/', views.head_dashboard, name='head_dashboard'),
   path('teamlead-dashboard/', views.teamlead_dashboard, name='teamlead_dashboard'),
   path('executive-dashboard/', views.executive_dashboard, name='executive_dashboard'),
   path('data_manager-dashboard/', views.data_manager_dashboard, name='data_manager_dashboard'),
   path('telecaller-dashboard/', views.telecaller_dashboard, name='telecaller_dashboard'),
   
   path('departments/', views.departments, name='departments'),
   path('add-department/', views.add_department, name='add_department'),
   path('edit-department/<int:department_id>/', views.edit_department, name='edit_department'),
   path('delete-department/<int:department_id>/', views.delete_department, name='delete_department'),
   path('get-department-details/<int:department_id>/', views.get_department_details, name='get_department_details'),
   path('check-department-exists/', views.check_department_exists, name='check_department_exists'),

   path('designations/', views.designations, name='designations'),
   path('add-designation/', views.add_designation, name='add_designation'),
   path('edit-designation/<int:designation_id>/', views.edit_designation, name='edit_designation'),
   path('delete-designation/<int:designation_id>/', views.delete_designation, name='delete_designation'),
   path('get-designation-details/<int:designation_id>/', views.get_designation_details, name='get_designation_details'),
   path('check-designation-exists/', views.check_designation_exists, name='check_designation_exists'),

   path('login_requests/', views.login_requests, name='login_requests'),
   path('employee_register/', views.employee_register, name='employee_register'),
   path('check-company/', views.check_company, name='check_company'),
   path('get-departments/', views.get_departments, name='get_departments'),
   path('get-designations/', views.get_designations, name='get_designations'),
   path('approve_employee/<int:employee_id>/', views.approve_employee_request, name='approve_employee'),
   path('decline_employee/<int:employee_id>/', views.decline_employee_request, name='decline_employee'),
   path('check-email-employee/', views.check_email_employee, name='check_email_employee'),
   
   path('works/',views.dmh_works, name='dmh_works'),
   path('tasks/', views.task_page, name='task_page'),
   path('delete-task/<int:id>/', views.delete_task, name='delete_task'),
   path('register_client/', views.register_client, name='register_client'),
   path('clients/register/', views.add_client, name='add_client'),
   path('get-client-data/<int:id>/', views.get_client_data, name='get_client_data'),
   path('update-client/<int:id>/', views.update_client, name='update_client'),
   path('check_client_field/', views.check_client_field, name='check_client_field'),
   path('delete-client/<int:client_id>/', views.delete_client, name='delete_client'),
   path('create-work/<int:client_id>/', views.create_work, name='create_work'),
   path('registered_work/', views.registered_work, name='registered_work'),
   path('edit_work/<int:id>/', views.edit_work, name='edit_work'),
   path('delete_work/<int:work_id>/', views.delete_work, name='delete_work'),
   
   path("dm_employees_home/", views.dm_employees_home, name="dm_employees_home"),
   path('head/view-employees/', views.head_view_employees, name='head_view_employees'),
   path('head/allocate-employees/', views.head_allocate_employees, name='head_allocate_employees'),
   path('head/allocated-list/', views.head_allocated_list, name='head_allocated_list'),
   path('head/api/allocate/', views.head_api_allocate, name='head_api_allocate'),
   path('head/api/reallocate/', views.head_api_reallocate, name='head_api_reallocate'),
   path('update-employee-designation/', views.update_employee_designation, name='update_employee_designation'),
   
   path('head_myschedule/', views.head_myschedule, name='head_myschedule'),
   path('save_schedule/', views.save_schedule, name='save_schedule'),
   path("filter_today_schedule/", views.filter_today_schedule, name="filter_today_schedule"),
   path("filter_schedule_range/", views.filter_schedule_range, name="filter_schedule_range"),
   path("update-schedule-status/", views.update_schedule_status, name="update_schedule_status"),
   path("get_schedule/<int:id>/", views.get_schedule, name="get_schedule"),
   path("update_schedule/<int:id>/", views.update_schedule, name="update_schedule"),
   path("delete_schedule/<int:pk>/", views.delete_schedule, name="delete_schedule"),
   path('head_schemployee/', views.head_schemployee, name='head_schemployee'),
   path('save_employee_schedule/', views.save_employee_schedule, name='save_employee_schedule'),
   path("filter_emptoday_schedule/", views.filter_emptoday_schedule, name="filter_emptoday_schedule"),
   path("filter_emp_schedule/", views.filter_emp_schedule, name="filter_emp_schedule"),
   path("get_empschedule/<int:id>/", views.get_empschedule, name="get_empschedule"),
   path("update_empschedule/<int:id>/", views.update_empschedule, name="update_empschedule"),
   path('head_schefilter/', views.head_schefilter, name='head_schefilter'),
   path("filter_schedules/", views.filter_schedules, name="filter_schedules"),
   path('head_myleave/', views.head_myleave, name='head_myleave'),
   path("save-leave/", views.save_leave, name="save_leave"),
   path('head_leaverequest/', views.head_leaverequest, name='head_leaverequest'),
   path("update-leave-status/", views.update_leave_status, name="update_leave_status"),
   
   path("action_taken/",views.action_taken,name="action_taken"),
   path("save_actionTaken/", views.save_actionTaken, name="save_actionTaken"),
   path("edit_action_taken/<int:id>", views.edit_action_taken, name="edit_action_taken"),
   path("edit_actionTaken/<int:id>", views.edit_actionTaken, name="edit_actionTaken"),
   path("feedback/", views.feedback, name="feedback"),
   path("save_feedback/", views.save_feedback, name="save_feedback"),
   path('head/leaves-employees/', views.head_view_leaves, name='head_view_leaves'),
   path('head/actiontaken-employees/', views.head_view_actionTaken, name='head_view_actionTaken'),

   path("admin_employees/",views.admin_employees,name="admin_employees"),
   path("employee_views/",views.employee_views,name="employee_views"),
   path('edit_employee/',views.edit_employee,name='edit_employee'),
   path('resigned/',views.resigned,name="resigned"),
   path('update_employee/', views.update_employee, name='update_employee'),
   path('re_approve/',views.re_approve,name='re_approve'),
   path('allocated_lists',views.allocated_lists,name='allocated_lists'),
   path('employee_leaves',views.employee_leaves,name='employee_leaves'),
   path('employee_schedule',views.employee_schedule,name='employee_schedule'),
   
    path("tl_schedule",views.tl_schedule,name="tl_schedule"),
    path("schedule/", views.tl_schedule, name="tl_schedule"),
    path("toggle-schedule/<int:id>/",views.toggle_schedule),
    path("delete-tlschedule/<int:id>/",views.delete_tlschedule,name="delete_tlschedule"),
    path("tl_empschedule/", views.tl_empschedule, name="tl_empschedule"),
    path('delete-empschedule/<int:id>/', views.delete_empschedule, name='delete_empschedule'),
    path("tl_leaves/", views.tl_leaves, name="tl_leaves"),
    path("tl_action/", views.tl_action, name="tl_action"),
    
    #  Executive
    path('executive_schedule',views.executive_schedule,name='executive_schedule'),
    path('register_executive_schedule',views.register_executive_schedule,name='register_executive_schedule'),
    path('exclusive_schedule_finished',views.exclusive_schedule_finished,name='exclusive_schedule_finished'),
    path('exclusive_schedule_edit',views.exclusive_schedule_edit,name='exclusive_schedule_edit'),
    path('delete_executive_schedule/<int:id>',views.delete_executive_schedule,name='delete_executive_schedule'),
    path('executive_view_schedule',views.executive_view_schedule,name='executive_view_schedule'),
    path('executive_leave',views.executive_leave,name='executive_leave'),
    path('executive_feedback',views.executive_feedback,name='executive_feedback'), 
    path('executive_complaints',views.executive_complaints,name='executive_complaints'),
    
    path('telecaller_leave/', views.telecaller_leave, name='telecaller_leave'),
    path('telecaller_action_taken/',views.telecaller_action_taken,name='telecaller_action_taken'),
    path('telecaller_feedback/',views.telecaller_feedback,name='telecaller_feedback'),
    path('telecaller_complaints/',views.telecaller_complaints,name='telecaller_complaints'),
    
    path('employee_views_tele/', views.employee_views_tele, name='employee_views_tele'),
    path('employee_views_executive/', views.employee_views_executive, name='employee_views_executive'),
    path('employee-detail/<int:id>/', views.employee_detail, name='employee_detail'),
    path('view_employee_schedules/', views.view_employee_schedules, name='view_employee_schedules'),
    path("head_view_resigned",views.head_view_resigned,name="head_view_resigned"),
    path("view_employee_feedback",views.view_employee_feedback,name="view_employee_feedback"),
    
    path('dm_work_allocate',views.dm_work_allocate,name='dm_work_allocate'),
    path('work-allocate/<int:id>/', views.work_allocate_page, name='work_allocate_page'),
    path('remove-allocation/<int:work_id>/<int:emp_id>/',views.remove_allocation,name="remove_allocation"),
    path("get-task-details/", views.get_task_details, name="get_task_details"),
    path('edit_task/', views.edit_task, name='edit_task'),
    path('delete-client-task/', views.delete_client_task, name='delete_client_task'),
    path('edit_lead/', views.edit_lead, name='edit_lead'),
    path('delete-lead/', views.delete_lead, name='delete_lead'),
    path('team-lead-tasks/<int:lead_id>/<int:work_id>/', views.team_lead_tasks, name='team_lead_tasks'),
    path('delete-work-allocation/<int:allocation_id>/', views.delete_work_allocation, name='delete_work_allocation'),
    path('delete-task-allocation/<int:allocation_id>/', views.delete_task_allocation, name='delete_task_allocation'),
    path('delete-category/<int:id>/', views.delete_category_allocation, name='delete_category_allocation'),
    path('edit-lead-collection/<int:allocation_id>/',views.edit_lead_collection,name='edit_lead_collection'),
    path('delete-lead-collection/<int:allocation_id>/',views.delete_lead_collection,name='delete_lead_collection'),
    path('pending_works/',views.pending_works,name='pending_works'),
    path('work_progress/',views.work_progress,name='work_progress'),
    path('client-details/<int:client_id>/', views.client_work_details, name='client_work_details'),
    
    path('lead-fields/<int:lead_id>/', views.lead_fields_page, name='lead_fields_page'),
    path('add-required-field/', views.add_required_field, name='add_required_field'),
    path('lead-data-page/', views.lead_data_page, name='lead_data_page'),
    path('download-lead-format/<int:lead_id>/',views.download_lead_format,name='download_lead_format'),
    path("client-lead-data/<int:lead_id>/",views.client_lead_data,name="client_lead_data"),
    path('apply_lead_action/',views.apply_lead_action,name='apply_lead_action'),
    path('verified-leads/', views.verified_leads_page, name='verified_leads_page'),
    path("get-client-categories/",views.get_client_categories,name="get_client_categories"),
    path("transfer-verified-leads/",views.transfer_verified_leads,name="transfer_verified_leads"),
    path("transferred-leads/",views.transferred_leads_page,name="transferred_leads_page"),
    
    path("tl_works_home/", views.tl_works_home, name="tl_works_home"),
    path("teamlead_allocated_works/", views.teamlead_allocated_works, name="teamlead_allocated_works"),
    path("teamlead_pending_works/", views.teamlead_pending_works, name="teamlead_pending_works"),
    path("executive_work_home/", views.executive_work_home, name="executive_work_home"),
    path("executive_new_work/", views.executive_new_work, name="executive_new_work"),
    path("accept_task/<int:id>/", views.accept_task, name="accept_task"),
    path("executive_task_ongoing/", views.executive_task_ongoing, name="executive_task_ongoing"),
    path("executive_adddaily_work/<int:id>/", views.executive_adddaily_work, name="executive_adddaily_work"),
    path("executive_adddailywork/<int:id>/", views.executive_adddailywork, name="executive_adddailywork"),
    path("executive_view_dailywork/<int:id>/", views.executive_view_dailywork, name="executive_view_dailywork"),
    path('delete-allocation/<int:id>/', views.delete_allocation, name='delete_allocation'),
    path('get-dailyworks/<int:task_id>/', views.get_dailyworks, name='get_dailyworks'),
    
    path('update_verification/', views.update_verification, name='update_verification'),
    
    path('tl_individualwork_home/', views.tl_individualwork_home, name='tl_individualwork_home'),
    path('tl_individualwork/', views.tl_individualwork, name='tl_individualwork'),
    path('accept_task1/<int:id>/', views.accept_task1, name='accept_task1'),
    path('tl_task_ongoing/', views.tl_task_ongoing, name='tl_task_ongoing'),
    path("tl_adddaily_work/<int:id>/", views.tl_adddaily_work, name="tl_adddaily_work"),
    path("tl_adddailywork/<int:id>/", views.tl_adddailywork, name="tl_adddailywork"),
    path("tl_view_dailywork/<int:id>/", views.tl_view_dailywork, name="tl_view_dailywork"),
    path("executive_weekly_progress", views.executive_weekly_progress, name="executive_weekly_progress"),
    path("executive_add_weekly_report", views.executive_add_weekly_report, name="executive_add_weekly_report"),
    path("executive_monthly_progress", views.executive_monthly_progress, name="executive_monthly_progress"),
    path("executive_add_monthly_report", views.executive_add_monthly_report, name="executive_add_monthly_report"),
    path('verify-report/', views.verify_report, name='verify_report'),
    path('head_weekly_progress/', views.head_weekly_progress, name='head_weekly_progress'),
    path('head_monthly_progress/', views.head_monthly_progress, name='head_monthly_progress'),
    path('progress_updation/', views.progress_updation, name='progress_updation'),
    
    path('data-manager-dataBank/', views.data_manager_dataBank, name='data_manager_dataBank'),
    path('data-manager-allocation/', views.data_manager_allocation, name='data_manager_allocation'),
    path('follow-up/', views.data_manager_followup, name='data_manager_followup'),
    path('get-categories/', views.get_categories_by_client, name='get_categories'),
    path('allocate-leads/', views.allocate_leads, name='allocate_leads'),
    path('lead-details/<int:id>/', views.lead_details, name='lead_details'),
    path('unassign-lead/<int:id>/', views.unassign_lead, name='unassign_lead'),
    path('bulk-unassign-leads/', views.bulk_unassign_leads, name='bulk_unassign_leads'),
    path('add-followup-status/', views.add_followup_status),
    path('delete-followup-status/<int:id>/', views.delete_followup_status),
    path("accept-leads/", views.accept_leads, name="accept_leads"),
    path("telecaller_allLeads/", views.telecaller_allLeads, name="telecaller_allLeads"),
    
    path('management/action-taken-list/', views.admin_action_taken_list, name='admin_action_taken_list'),
    path('management/feedback-list/', views.admin_feedback_list, name='admin_feedback_list'),
    path('management/complaints-list/', views.admin_complaints_list, name='admin_complaints_list'),

    path("telecaller_followups/", views.telecaller_followups, name="telecaller_followups"),
    path("telecaller_followup_updates/<int:id>/", views.telecaller_followup_updates, name="telecaller_followup_updates"),
    path("change_lead_waste/<int:id>/", views.change_lead_waste, name="change_lead_waste"),
    path("change_lead_close/<int:id>/", views.change_lead_close, name="change_lead_close"),
    path("change_lead_recall/<int:id>/", views.change_lead_recall, name="change_lead_recall"),
    path("change_lead_joined/<int:id>/", views.change_lead_joined, name="change_lead_joined"),
    path("telecaller_wasteLeads", views.telecaller_wasteLeads, name="telecaller_wasteLeads"),
    path("telecaller_closedLeads", views.telecaller_closedLeads, name="telecaller_closedLeads"),
    path("telecaller_followup_details/<int:id>/", views.telecaller_followup_details, name="telecaller_followup_details"),
    path("telecaller_report_details/<int:id>/", views.telecaller_report_details, name="telecaller_report_details"),
    path("telecaller_reportLeads", views.telecaller_reportLeads, name="telecaller_reportLeads"),
    
    path('platform-management/', views.platform_management, name='platform_management'),
    path('platform-leads-details/', views.platform_leads_view, name='platform_leads_view'),
    path('platform-reports/', views.platform_reports, name='platform_reports'),
    path('notification-management/', views.notification_management, name='notification_management'),
    path('today-new-leads/', views.today_new_leads_view, name='today_new_leads_view'), 
    path('today-allocations/', views.today_allocations_view, name='today_allocations_view'),

    path("delete_all_followups/<int:id>/", views.delete_all_followups, name="delete_all_followups"),

   
   
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
   

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)